package com.biosimilarity.scalate.model.WhiteRabbit.Absyn; // Java Package generated by the BNF Converter.

public class Stipulation extends Expression {
  public final VariableExpr variableexpr_;
  public final Expression expression_;

  public Stipulation(VariableExpr p1, Expression p2) { variableexpr_ = p1; expression_ = p2; }

  public <R,A> R accept(com.biosimilarity.scalate.model.WhiteRabbit.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.scalate.model.WhiteRabbit.Absyn.Stipulation) {
      com.biosimilarity.scalate.model.WhiteRabbit.Absyn.Stipulation x = (com.biosimilarity.scalate.model.WhiteRabbit.Absyn.Stipulation)o;
      return this.variableexpr_.equals(x.variableexpr_) && this.expression_.equals(x.expression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.variableexpr_.hashCode())+this.expression_.hashCode();
  }


}
